"use client";

import { useState } from "react";

export default function ImageGenerator() {
  const [prompt, setPrompt] = useState("");
  const [image, setImage] = useState("");
  const [loading, setLoading] = useState(false);

  async function generateImage() {
    if (!prompt.trim() || loading) return;

    setLoading(true);
    setImage("");

    try {
      const response = await fetch("/api/image", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ prompt }),
      });

      const data = await response.json();

      if (data.image) {
        setImage(data.image);
      } else {
        alert(data.error || "Image generation failed.");
      }
    } catch {
      alert("Unable to connect to NOVA AI.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="min-h-screen bg-[#070812] px-5 py-10 text-white">
      <div className="mx-auto max-w-4xl">
        <div className="mb-8 text-center">
          <div className="text-5xl">🎨</div>

          <h1 className="mt-4 text-4xl font-bold">
            NOVA Image Generator
          </h1>

          <p className="mt-3 text-gray-400">
            Describe your idea and NOVA will create an image.
          </p>
        </div>

        <div className="rounded-3xl border border-white/10 bg-white/5 p-5">
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="Example: A cinematic futuristic city at night..."
            rows={6}
            className="w-full resize-none rounded-2xl border border-white/10 bg-black/20 p-4 outline-none placeholder:text-gray-600 focus:border-purple-500"
          />

          <button
            onClick={generateImage}
            disabled={loading || !prompt.trim()}
            className="mt-4 w-full rounded-xl bg-purple-600 px-6 py-3 font-semibold hover:bg-purple-500 disabled:opacity-40"
          >
            {loading ? "Creating image..." : "Generate Image"}
          </button>
        </div>

        {image && (
          <div className="mt-8 overflow-hidden rounded-3xl border border-white/10 bg-white/5 p-3">
            <img
              src={image}
              alt="Generated by NOVA AI"
              className="w-full rounded-2xl"
            />
          </div>
        )}
      </div>
    </main>
  );
}
